apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  instances: 1
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
  storage:
    storageClass: csi-rbd-sc
    size: 8Gi
