apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  # - namespace.yml
  - cnpg.yml
helmCharts:
  - name: vaultwarden
    repo: https://guerzon.github.io/vaultwarden
    version: 0.31.6
    namespace: vaultwarden
    releaseName: vaultwarden
    valuesFile: values-vaultwarden.yml
