apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yml
  - sealed-secret-oidc.yml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 70.0.2
    namespace: monitoring
    releaseName: kube-prometheus-stack
    includeCRDs: true
    valuesInline:
      grafana:
        sidecar:
          dashboards:
            enabled: true
            searchNamespace: ALL
        grafana.ini:
          server:
            domain: grafana.adb.sh
            root_url: "https://%(domain)s/"
            serve_from_sub_path: false
          auth:
            disable_login_form: true
          security:
            disable_initial_admin_creation: true
          auth.generic_oauth:
            enabled: true
            allow_sign_up: true
            auto_login: false
            name: Gitea
            client_id: "$__file{/etc/secrets/auth_generic_oauth/client_id}"
            client_secret: "$__file{/etc/secrets/auth_generic_oauth/client_secret}"
            scopes: "openid profile email"
            auth_url: https://git.cybre.town/login/oauth/authorize
            token_url: https://git.cybre.town/login/oauth/access_token
            api_url: https://git.cybre.town/login/oauth/userinfo
        extraSecretMounts:
          - name: auth-generic-oauth-secret-mount
            secretName: auth-generic-oauth-secret
            defaultMode: 0440
            mountPath: /etc/secrets/auth_generic_oauth
            readOnly: true
        persistence:
          type: sts
          enabled: true
          storageClassName: csi-rbd-sc
          accessModes:
            - ReadWriteOnce
          size: 10Gi
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - grafana.adb.sh
          path: /
          tls:
            - secretName: grafana-cert
              hosts:
                - grafana.adb.sh
          annotations:
            "cert-manager.io/cluster-issuer": "lets-encrypt"
            "traefik.ingress.kubernetes.io/router.middlewares": traefik-redirect-https@kubernetescrd
