apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - sealed-secret-rbd.yml
  - sealed-secret-cephfs.yml
helmCharts:
  - name: ceph-csi-rbd
    repo: https://ceph.github.io/csi-charts
    version: 3.13.0
    namespace: ceph-csi-rbd
    releaseName: ceph-csi-rbd
    valuesInline:
      selinuxMount: false
      csiConfig:
        - clusterID: "eb00303d-49ad-4df9-aab9-78c28322d497"
          monitors:
            - "10.10.0.20:6789"
      storageClass:
        create: true
        name: csi-rbd-sc
        clusterID: "eb00303d-49ad-4df9-aab9-78c28322d497"
        pool: talos-csi
        imageFeatures: layering
        provisionerSecret: csi-rbd-secret
        provisionerSecretNamespace: ceph-csi-rbd
        nodeStageSecret: csi-rbd-secret
        nodeStageSecretNamespace: ceph-csi-rbd
        reclaimPolicy: Retain
        allowVolumeExpansion: true
  - name: ceph-csi-cephfs
    repo: https://ceph.github.io/csi-charts
    version: 3.13.0
    namespace: ceph-csi-cephfs
    releaseName: ceph-csi-cephfs
    valuesInline:
      selinuxMount: false
      csiConfig:
        - clusterID: "eb00303d-49ad-4df9-aab9-78c28322d497"
          monitors:
            - "10.10.0.20:6789"
      storageClass:
        create: true
        name: csi-cephfs-sc
        clusterID: "eb00303d-49ad-4df9-aab9-78c28322d497"
        fsName: talos-csi-cephfs
        pool: talos-csi-cephfs_data
        provisionerSecret: csi-cephfs-secret
        provisionerSecretNamespace: ceph-csi-cephfs
        nodeStageSecret: csi-cephfs-secret
        nodeStageSecretNamespace: ceph-csi-cephfs
        reclaimPolicy: Retain
        allowVolumeExpansion: true
