apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ceph-csi
resources:
  - namespace.yml
helmCharts:
  - name: ceph-csi-rbd
    repo: https://ceph.github.io/csi-charts
    version: 3.13.0
    namespace: ceph-csi
    releaseName: ceph-csi-rbd
  - name: ceph-csi-cephfs
    repo: https://ceph.github.io/csi-charts
    version: 3.13.0
    namespace: ceph-csi
    releaseName: ceph-csi-cephfs
