apiVersion: v1
kind: Namespace
metadata:
  name: ceph-csi-rbd
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged

---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-csi-cephfs
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
