---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ceph-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgC5VqvFwNSkaazM4n302eT8NScPGLFnkKSDJ/9PPG+tbcP0vSlzkLjQW2r6t0OpEz3L0mpUOeiX1JhBZWClrzOP8yIOlws0KEPJGyyNTwFShmS2BZkB7HScvlsksin2pb4r//aqvqxVbKXdkxQXGCMB0bqEqZDU6UNkUrwVG61GAEDeMJVaoklEaz6W7u9V/GJn537D4JT4iRyZ0dlQT2d5c8EsaqzooXr7H/+55tT0wqufGuGNuh1xA+Eq7LOuQjLBPKwCD8XO935VlsTE1wMGh28RvrBFN//n4KfdB+crwiSoxqlkah1HZBlEkBMCZclu5rtGw5d9D48//78NK2kDEaL1tJJ/vGz2R/N0e0dDdlcANytY7SFHdCgVkQa8fi59xMcE2CpTe9SbbMAUe/UryGxKxHBI7R+GKqhT+rNrY02AmZj+bgWZk6LilhWrRfmpyt1P+HXFThGz8hAl44fcUivr06zDWea4+t2Os2T0sL2eXXVib90SuXucoq3byeJvOOOF3tRrJnZ0EyLi2vDH+FHMtA6gAxjeePbLSk4LCNZtNwNmj1lkM/jlknN3yMe2tZohOU8hCvdAXBmR4o/hNg7iw4NkPblFdD6BNxrhVPI4bjmuB4X9wyAUMWM/BtUWgrlS1qSvB5CB1+uoy5BfddFcp+WIfSRd28xMasDy40gMYiabMrVYGQmZPMoIC93Cdpo=
    userKey: AgBxkJBHHK//cJe++dYtiP7muDiiCld2ZF4ZtW8FcLFOpKqYNe5YDWQ+mpWVwVWWBZh368VrAdX3El8W6cRy5uZVCi7Sel4gulDlP8glvDpxsiwQHcqpdZAcihgNuHATzVsK4UwoOkbHT99r/tLGQ+yznrgzueaipt6t+zBUBKzTvY/3uoRw/wsbAZgjtO+xKTS1W5FxHctm4bm0omCaBJskhYfLxufROBITIyeUu/N9Od3+G0rOvnVe0kL57kMv/IVGioycqkiU27C3iBDsPAOjCCI+OO8ZmviTcXFlN5WAfzDIvmn7Ne5Ln6wK8HUys3czizYLQy5QO+OcAG9J7X07z1/JA9XmpB/EYLTiIla9cqolK5+5fNPPKWv0UjgzBF5UOUCOufkh8vmY+u9zv7ChC70ofgUWnGjpoo8Vjr0qKqlZKRUz2frDIgaaxBztWiGv7wCqGat9WBW5NPBZGC3qZbwSJOV47nnCgJLlqkSGf8yHxeEcS5CrD0XRf3AL7SXKZc/NnaABDBGK2HSd4MQgFdX9nVEQRiWE0ZgJDLF1x941/GOBwWROo8JesO++/6VB/hIOXuaGXwFauPAvx9VQPixH2Bqe7/g/8YhWjS/NiUZjmGOUrOHz28Dpj1PhncXT3r10mkXros+QYsE2DGqKeRYbLCly1ybZTYJ73Rw1mZ9/pvIp5/HDmjctZZ3JXhTBik7VkEPFP9KiFxj0hf1NwFEryBIV25icOSasrKstj/CDUrAIaG3W
  template:
    metadata:
      creationTimestamp: null
      name: ceph-secret
      namespace: ceph-csi-rbd
    type: Opaque
