---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ceph-secret
  namespace: cehph-csi
spec:
  encryptedData:
    userKey: AgCbFX0HCgVAix3drx2MJCjMaNcpKenckxBX4gCScuzzAEVGMc0npu8NtismtmM7txQkm63/c5oA6+3EcX/CuYD6/tJgcxiQ2bVZ5bdqkC+id3xWhx/6e7Hhb0w56/vGD3/Qj8w8rg9QIsOoqfGVb3ewnYFZzkLmNN7adh2g3Sl3ulEXNwWx8x0KwzOZ+b4Btr4CB2Z/7vmeE7zDtiq3AnWBa7P9EPE4c/umGu4a8BouQlXuWJV/LZbQAEnHDfo8zOQmFO56BpQfCVtwPphvoHPBM6VZOvUnU/gVTxhbexiN3KldJMRDnwv5Hz6EuPygnPzdbXrL3IO0oeyETPsrzrKzO7EqIN6tj1cylVUCe9gktxHl7YB2l5cEDZdfe2DvFEzXoxpmbI9OC5Yk+Gw4RsEYLpTZKpp9Dr7YWCx+puf+npfBa6yJOiN8vfEU3wQyIt1X8dUMHZy40kHW8UN9l3vRYdIZUQ3asuXrHpgls92BpwLawk+F/UxVhP+x8WLGWLjqAOHje/NVkw8KwAXEAqOADXj63oB7/2HuUaIh/1+eMJo0Y1CYKnbAiBSnARMjArHOZXLa6GzXxiXabH1xtHUHdB0I31P5yHVCZvEWkXi7eBlcqmAn8hKVNM/a5YZL3BEN25/tAt6FGHiM7Ago30rlsBhZafWK05T0nvnxrQow68rJabGJMESHCNmbJCIX/VclCSZUrr9iklXWikvWh+OyLeArldlja/JlAg6rO79E7fk4ZbioR7Wr
  template:
    metadata:
      creationTimestamp: null
      name: ceph-secret
      namespace: cehph-csi
    type: Opaque
