---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgB1oxyG+9k7vfvRElGe0l5QfmFL651yd5CIbyrBdJAaDpmuAxA998hw62A76IF2YEO8sddkfB5FXTkrS0oJQVUxBDxxQYoz4W/GwClHoiZwFLwrIgvl2Fx8MEru2SAmVp8jRP3khI8Fs/wT5pifQAa3dBKi2AdKsyJakQSqGviWPSoLa8phMk2w3dYSQc8iSuPDuJnPubdsChyI5mNwMzazEks7YJVPjirU8u5yLrCrVyxovlTdIngA1y00RtUmJLGFmA2LB3LXn4odfhjPzGXRVRwwR0B0f1wdiENCJzDC0DH91Bo376mgroWMcNjPl0s2ehGG1ujYxxfy2SohifpiU3mIQMmzoWFqZxdpzfK/sd4K9O3+61bborXEiszmKCtXZDcsjjZ2fS6QosrqPO/BJVtJMLODPmfsM+bJBC50wsQPucKuIrHMC66tm+erQlGdtebMw3oTFyuF8lHevjzz6gXynhdrqWTuU6vyXZBKSPXUO6xzhsNlC0EPpmzaWUP7DF6yZbwsU+JiG5Bloi5OhmErBoUXdWDF6TxHOADvFKtCAeMPA2jUn/W8PUNPesDlLngQYCNXGcLLyHcim72quvTvHMJlxZfPpn7To00L5mwmeEZ1rHYju9VzqwIv8INBVjIUrH0+CIIB1Csp/YOsPOi2HNdtvpmDl+gHHw1pYo0LMAsdIVhCjzRzwpsH9l0MfiY=
    userKey: AgB/Q5DKoN2nMn3XD6tPZ/FtO6nDGy90EHN15UwV1S5Gy+E07jPqMxwCHV910lyiM/fI6eo2vWo/gyhEDUeIBCfAO6IRFv/az2pxoe8XWo2bCXmeNMxwAx1DEGqsTjqHhz5xyQ0/y4NqSZBNxu3YTORaxUG/6PA8BB4fkxTwgNuY9kQ/X896V7K2/DyDErv45vNt4QNoYpGwBOZP2y+Do75ceTkA9mbKoaluzdaMGxNeOxjqX4gSmajfI/XUhlpCKtc2vgZnec8W3PrkSM2TVACPmFePzWDA6QKRyYj2Q+fdmF3BIeTgk31n4seAS5hZVb30ErEJ66rGaq8PVwA3Hq1XaUPPVk69c0ehT+N4MEx06FRZUONy+qU+IFGlC5R+o4T1Z/FUGBsEljO8Q14ckI6r1bIXaZGMXVs8TQgqtO02mH5TjwDbHCdUCtb7TM5C0nkuQoPmm2C+wWhfqFDIc6rb1y4vtZOQKjwnz4qqYGtMEX3xA6ORCN4yzsP6MqmAs5gbWnciWYMWMyschkN56XhgSQW3+vK4H9emVbatw2DJev9+GhuwTveK0/0+2ZeCwqgtmss/B5LF4KO75zaIzdEzFTgqU9VYW6aphey3WQ9S4/v2MeaTE8yjzGV8BNnfIXJBQU6/m5itNtzRWK1J3/pH66C9Jz+WdJhs9yjpqD6mODpJ94vJt6iOmWAhb7BB2Tit8IXDUn+vPRncyM4NuSgVlkf4PwReXfB0N38PAoYUeMMHxh//KWUE
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
    type: Opaque
