---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ceph-secret
  namespace: ceph-csi-cephfs
spec:
  encryptedData:
    userId: AgBunw5rII/CJ9oIZ5Lax168as5/r4p1a/90m3MjreIgUHYbMwlrh+CFZso5ICWqjPj5s9WM6t4k0U5AdIozLFNhpfnN/08nRFli4TmyFUsQ5d0cOvtmsQVO91e0P3PzFjbo6zyvhqU2PFjSVWRH8TnZeRdzLaR0MMCIa4TanFs4/hqrrwTpKC0BzkWs73wkf3cnX8JLvHgZGilGI2i+UPNUwNyoHGs7TDfCemImD9xgw/m0EpXbgOr2X4DlJSvU5rgQ2H9GQA2uxiJVXR/Y/ZX1uHybel6Hxe6dR0eB4DIEZJ5F9QF+3MVFTtj1hm1fZjyXSjsrxIYd6YyptguXpk8lXWPEnXN+TXAFrGGo+f7w+cjUe28oMUhViPxrPWvKn51/ZH1b/8hZNrU3WFgyRcye4nTLMV0388/KeB0/lEUkwR3U5++Xf/d8cDV7qpS+tXm72Hfoa/0ISk330AtPcK5KYCQi9JtnJmc0eJ4V/UWwEWQY1zQn1xBvzQD0EuEQlJwSDkZQR6VR3zqhjbCrTbKJmAK+9osehWheiqFonDlNXCa2aW2HrrpG1Hd4mYMQXQMbC9ZxFqsCYY0ggXB4LmY5twf3BiVC0X/3oGuY9yNFXElWArL2rubvAJ2vJLgg7jIOggq9d23dO1eKI/Xi2NUp4PllDhmgBYe6LaONyoviwLw8VIeIOVFx1B9NflJGK1an2wxiN1mxF3c5
    userKey: AgCBu1aI9CgPw3kmi7mYMWIgtdxdTaEXPwfeyiSuIXkN1gYH/Z1l9tv7gzhvhdCupp572hLOd1T1gKTtt4PH49S5su3jLaDLHxRwVj6zfdERthA+DwjcVdzwEZTftTSkGrCVeEcdpssEb68ySkI0l4Msa0BuPw9W4AijTULLkZcXwfmLMrS1gVejqHquvtIAoe9LkrCn9dFaWnsV5OCvjjjnsXcCHyiJpnTurDji4CwqD5BUgfIDhAAlpz2xLDFCL1vncL+jE4EjSXHusonjmYUrJBofRqY4dimeqvqIRZA4oQBKKEmP0MjHosGqEdnptvN1OtwZsp5XkBUKwjg6YWtUTpyK9UUNvwmU+4v10bEXN8H7vqxm8pUwufrEudFvRUnAZSMozQhdCn+sGYz081OhqRblz+bUF+NDHGQ1oOwLw5MqnL6Pzj334cNM16Ns/JOTyy726ICspT57wQ7eWM/+7o263qTKBLlQjOTXlPZNJ65J/MAIoWVNv//Kv4G7xBc3gpuWV9QL43RXAmsNh5YbYd8s/Cer/K6KvuuNAIOJXmBteO9se3K4OsMNk05MtN8FM5faTfIzib98Yn2XLeEJWaxHkQGbfsXzmzynnn83Y72Z8NmvAgZEAVjYj/GJEsYCHtafL0PcybXQCtd6JbvGYloqNE8qee6AcJSTnaewmsPG7YxbrWM85Ngclk7a6EEPAoN5iPu5sbktInRUwhvPc+gaimNOswEyJviukr67UralP2beQoVF
  template:
    metadata:
      creationTimestamp: null
      name: ceph-secret
      namespace: ceph-csi-cephfs
    type: Opaque
