apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
resources:
  - namespace.yml
helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.17.0
    namespace: sealed-secrets
    releaseName: sealed-secrets
    includeCRDs: true
