apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yml
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 33.2.1
    namespace: traefik
    releaseName: traefik
    includeCRDs: true
