apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: false
    contour:
      enabled: true
  config:
    network:
      ingress-class: "contour.ingress.networking.knative.dev"
      external-domain-tls: "Enabled"
      http-protocol": "Redirected"
    domain:
      "kn.cybre.town": ""
    certmanager:
      issuerRef: |
        kind: ClusterIssuer
        name: lets-encrypt
