apiVersion: cert-manager.io/v1
kind: "ClusterIssuer"
metadata:
  name: "lets-encrypt"
  namespace: operators
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "admin@adb.sh"
    privateKeySecretRef:
      name: "letsencrypt-account-key"

    solvers:
      - selector: {}
        http01:
          ingress:
            class: "traefik"
