apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: palworld-01
helmCharts:
  - name: palworld
    repo: oci://ghcr.io/twinki14/palworld-server-chart/
    version: 0.30.1
    namespace: palworld-01
    releaseName: palworld
    valuesInline:
      server:
        resources:
        limits:
          cpu: 2
          memory: "6Gi"
        requests:
          cpu: 1
          memory: "4Gi"
        storage:
          main:
            size: 12Gi
            storageClassName: "csi-rbd-sc"
        service:
        enabled: true
        type: LoadBalancer
