apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mastodon-db
  namespace: mastodon
spec:
  instances: 3
  bootstrap:
    initdb:
      database: mastodon
      owner: mastodon
  storage:
    storageClass: csi-rbd-sc
    size: 64Gi
