---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: mastodon
spec:
  encryptedData:
    password: AgCVkCEl3KW/cOWtfdsY76d1tZ2LmYoViqUzbuVBTNDrL+CHvJf/6K3oI+B6WxTgI+MuuoEpM4H/Ob+MXA6NoXmbYb9K+gwXMxkLrTYVk8X3WxwArpIQ/oc5dqGsiiVPAYYbrrhs/bAbRQrIG0pTEMKxFpCnIzOIVZdr/wL1u7HurBhmszuYY0I0itKhqwituGRhIgG8KZrxfLOI7FQsCDo2ii/wVmIUZJWlKR9dN2sqy4ZNpfqoOr2TsoBlWpUCsF2S8jKnH+OziOSISoQwbWN1ci+cGmYRHDVTjwtz1GUenXUH2kfLxsZSuB99NL4p28f6W74rUB4nGf9GCJyLHsaqt979e9gF5YQlw9rTj+NFkgSiXhgrvzTj4f3IdMFOcirk6lfghUdDUU72gsPBbfSG+IlFcaeup3Aa151wSM1V0K8KVqKEjZxnJwyMq1ypaJd8ISrI3de4g0pqGurZNGRiQ1IY0NE0HqDBN7lDg+n6XOgZQ4gO8sbqmv2c/pwXjcie4CXJTLCxswpJb4RCFs7rl/Lu4QAYygKTMnXFYhRIIAZhmdGKagof6N+G7zgSlHHD0+t5N6iDa5DAF4eCqmZIvNc3/P/FH7LGZC2KTvJneCES+2BWLcDu6cTKRGJUNK1zGUiXdP/wmT7x3XS4llM592B6U7amRqS8odQXuRXsYNTfRVp0TMkraswJsHuBqknEdmWdCk8Sn4GbHDgNWWH9XVfY4x0w5piH8PhpFntR+g==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: mastodon
    type: Opaque
