---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mastodon-smtp
  namespace: mastodon
spec:
  encryptedData:
    password: AgCWRXxN29Eev12ycrkbgw3XzFAC9hodtI4KQX6Wco9EBX6/t7dxrJnAmodxgzxHIrXNEvM7w4gxG1oqbUJ8HYYvsxjSzsD7Y1qyPp7IoM2QM1ToxVnAZUrBOczu9Wc3in6S/ZJ/3yuiXOUFFVwj9zMrvO1pc0iZGWcOKqr31L30zCFK06JXjtYQXbenmnQx4m8qme56PWerxB9Vb/9rcoo69libXgOIWLjDMTkz4wNQIjAeu0uNz5KpqZA5by/jZFMT3XnqS53xw2Ok4/94KnZWYCMx9TstQpqhCV+eaecqdufzeUYspKreY8ylyS4E7vBeTGpQ16zGqK7KE0IqfpYHNDmfPlo27YE9ovTQ2RovnE4apO5q80iIP/IbdC9ZmDH54kdQ+e9oFwvhtE7rnTf1+ZAFYavASLxgqh3kvFZ8TE5J9gjCXU7aZWfT+X0xkhOfDfnPU2EiGEr0olmrWuaVOoZRd2+ArIEFcR0ZMprembS/JFY2tqu/CfoI0uAzFFhERCcqTPWgXkG8BAi6m6KGGZ2yciLEIznzJMjAppi3DcogjbunnyYWDYuswAAPT4mCwBptNb67J3eL8WTcRLdEbSHJRofn4l++Rsamrtk/tW13xOdE0zRql3DZXNv0wwg5a3knqvrwgiiinoGWSOR9E94Ysy+gzfZ6vy2X9d11fh3UqzWKhayoVyET3e9f4SUrQxAsXuPJtd44jzsV/VU=
    username: AgBzBb1LpnPYYmXkxoYgViuIMqkmXev7LG9xhNapSKSTNlycb8qPHDrP9SicklVfs5DjyY+w800FuMyvZ7m1VwpODTOV547D0InWUbkxogdNNtYrMnhKdd1UQT++nn7VvDz3m21qRmSycyTxhJAlihslPi93B1pFGTgWBokQAomjOY903LbOymMTD0r15grXC+85g0z46Vdrvjovr1BWp7za4SeYol/Gf1CfnNUFj8VPuPASIrE6fAVioFAIDqqB4cCEnPlUSWjyKDctUzY6i7j8DveFPXmTHXT1kTlPcrsUqsi+NNm8dBzQjJ2bwcuuvBQaKWq7gXddgIbzu+zOqVgAqUAydxbpTFPgE2zcnht/YhEidwxeE3NthsHMcBCsaAkmUDlqd6m3FxcCyqdSAME1TGufgW4dMv2D62xLaY9F54q4zVAFVkzLIFLFaLuEFxsGyRBCyXLI70T2gDwVCT+D9QXEfS50yNbgt2bfjYraVbk2746C3JiAY2TlhgvuCHFkw4QOoN2EOkYDGFdwuAtOJA9ckyXLQUmiunZ69zMl/W+r1g4wNv39zQkIKBbW0qnWXsCXcsNEyLF+0KDuY8mrmVHcbsQgLF4cZej2Q8COQsvnpP+bTMJX5dpoQTu1oCPLFiTT5M4lhNYVEtDQ57BIIfsISyT5VyLUeakPVnuAaSu/v37fbqP34N6nYuvegrP5XqIU+n1tyAxhYT4WzBOHh+GQ/9grlcP3
  template:
    metadata:
      creationTimestamp: null
      name: mastodon-smtp
      namespace: mastodon
    type: Opaque
