apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: mastodon-valkey
  namespace: mastodon
spec:
  nodes: 3
  replicas: 0
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  exporterImage: ghcr.io/hyperspike/valkey-sidecar:8.1.4
  image: ghcr.io/hyperspike/valkey:8.1.4
  storage:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: csi-rbd-sc
