apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hedgedoc-db
  namespace: hedgedoc
spec:
  instances: 1
  bootstrap:
    initdb:
      database: hedgedoc
      owner: hedgedoc
  storage:
    storageClass: csi-rbd-sc
    size: 8Gi
