app:
  env:
    - name: "CMD_DOMAIN"
      value: "md.cybre.town"
    - name: "CMD_EMAIL"
      value: "true"
    - name: "CMD_ALLOW_EMAIL_REGISTER"
      value: "true"
    - name: "CMD_PROTOCOL_USESSL"
      value: "true"
    - name: "CMD_IMAGE_UPLOAD_TYPE"
      value: "filesystem"
    - name: "CMD_DB_URL"
      valueFrom:
        secretKeyRef:
          name: "hedgedoc-db-app"
          key: "uri"

podSecurityContext:
  fsGroup: 10001

resources:
  limits:
    cpu: "200m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

persistence:
  enabled: true
  size: "8Gi"
  storageClass: "csi-cephfs-sc"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    "cert-manager.io/cluster-issuer": "lets-encrypt"
    "traefik.ingress.kubernetes.io/router.middlewares": traefik-redirect-https@kubernetescrd
  hosts:
    - host: md.cybre.town
      paths:
        - path: "/"
          pathType: Prefix
          servicePortName: "http"
  tls:
    - secretName: hedgedoc-cert
      hosts:
        - "md.cybre.town"
