apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pretix-db
  namespace: silvatica-pretix
spec:
  instances: 1
  bootstrap:
    initdb:
      database: pretix
      owner: pretix
  storage:
    storageClass: csi-rbd-sc
    size: 16Gi
