apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: silvatica-pretix
resources:
  - namespace.yml
  - cnpg.yml
helmCharts:
  - name: pretix
    repo: https://helm.techwolf12.nl/
    version: 2025.4.0
    namespace: silvatica-pretix
    releaseName: pretix
    valuesFile: values.yml
