---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: silvatica-pretix
spec:
  encryptedData:
    password: AgBaANAM3FcuojHHk/Epn6UAyNB2ucGNAHPCytoykS3Fwgd5qjnlY/Cx1BN+7+0vlIxD7GAtnS2Ow4qbxNr6kA3ZvbACAuIATo4tRuvAhUdd7U+w2h1OTg58qdvPTB7kclF47iYHa+oSbzG4B/eR5JZXJ51LfzN0I8qLsAIw+dnOBho2bj2KzxOeZxEcerM8mI0A5gA0OcJ+629LC9O6z1r9b7c3DPSvN4z75Uk7Q3WPBb+/NWZ899dvy2t1CDbvD5tlm+UwWNBZ0GEhySTlHXu+lcGqueQd9bYuPrlT/6SOnNeCifQu3hcQ4Cv2JJxzTewiOMbfNobUmeQj15E+o9+pFHLhEuCFHO/w0aphYFVckSa6Nmae9b5e/BtN1GWg+Ddaq3a/sUXRZ36MeGCCbZsPdxxF2pDsCN6zAu1k73VsuDLOUI+fRTR8DdYOgJ5rKyvLGv9sC7Xs3YgA4PTSZ20yRHgyPm43UnKV6q5R1bDkaUCIyy/GVDvLdJeQBtZdf9JcAuxhhq//PMEJ8GY9VXLnXMDN+uewIS7ae3RfKwnJYbttCAY7Xp+UkygLMHI3cThkKmmAiXQk1+sa/rFeXOdKFWX8gpzsLzVsPtNRXr1dOhTSHUsNFscECJhYH5uebHeMQPNnOqQ8Fo5O89Ha+Z4H6FCuoKn1KjoLrWtnAXLAZzbVv9TvUkKtk+FhksXJu196MM090BLaLfQ9KJ18ka6e
  template:
    metadata:
      name: redis
      namespace: silvatica-pretix
    type: Opaque
