apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-db
  namespace: matrix
spec:
  instances: 3
  bootstrap:
    initdb:
      database: matrix
      owner: matrix
  storage:
    storageClass: csi-rbd-sc
    size: 256Gi
