apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-matrix-synapse-mediastore
  namespace: matrix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: csi-cephfs-sc
