---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: signingkey
  namespace: matrix
spec:
  encryptedData:
    signingkey: AgBDaO8UhmckIDW+46zSYDGZVMuosO07ted0g4tswzZ18Q5FvlawVRZns/qclCw3NAjzvxLs4oUFDkDhhacUdwb3xuLtn6i5Xaf6oKbU+5U2aZ7WffGwofP3Su4mZDYNn8iLXjXfWTNMu7+KRFOQ6Nu4aCdHgxhnLeJz8Q8+Kz5ZoSePG+YK4SLYaf2N78jRCHLVK4nv974dH+Z60tTjLApopZ1Dh0tUxOF3Jq+mve8glsb080G3d0BMQ5cWAcJvPm9XlrfrECbF7mvwLpz2iyXIOrSN3feGDY3w2dph2Rs5ad+7DQL+OIpirxSAroe1PN8Nf2PgPPj5lQYVmkTGTyiFrOelvg87ENldC+WdZb238PTRoMemQWL8YMNopifua970FLbrqNgzxYkJ0lkTAicwl2HhPMEoSJtyO7sCHTdZIcMn63/FvIYIKFLSOG6UeL5c7qZXp8iuhv45rgfdadmiqCbWNQgbmiiVxEv3OD7wub4Su4r39WUfQ4Oi6+k3FN/d+VrEODxJ1v8I/53sY3RX4ZwxpkH8MWlVEjZoboP/aL531l1eXJ7R6GBBSPvYXfG+y8YNPCw4inDVW7BpqxSe7KnknAfJd7uJzpgaZLpMQrMKrda4TKo0o9eLuZa3SKQCTKACGb32VnnI4+AB7eBZcrIkIN1pY+RB/ztBkPZl830vLsG1tcWNHsyCE3aQQP3Z5sN8DZhrJNolVFNd9GSY1Lz1W4SicJVD5Ke3hWDlcogQijLJCc/r2lMXOzjmuSBakjk67ZxzJoLS
  template:
    metadata:
      creationTimestamp: null
      name: signingkey
      namespace: matrix
    type: Opaque
