apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: palworld-01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: palworld-01
  project: default
  source:
    path: apps/palworld
    repoURL: git@github.com:adb-sh/talos-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
