apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cnpg
  namespace: operators
spec:
  channel: stable-v1
  name: cloudnative-pg
  source: operatorhubio-catalog
  sourceNamespace: olm
