apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
resources:
  # - namespace.yml
  - cnpg.yml
helmCharts:
  - name: gitea
    repo: https://dl.gitea.io/charts
    version: 10.6.0
    namespace: gitea
    releaseName: gitea
    valuesFile: values-gitea.yml
