namespace: argocd
resources:
  - namespace.yml
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm/
    version: 7.7.7
    valuesFile: values-argocd.yml
    namespace: argocd
    includeCRDs: true
    releaseName: argocd
